[tool.poetry]
name = "homefinancier-grpc"
version = "0.1.0"
description = "This library contains gRPC files and stubs for HomeFinancier's services"
authors = ["Enes Gulakhmet <e.gulakhmet@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
